language: python
python:
- '2.7'
install: pip install -r requirements.txt
script:
- pip install -U setuptools
- pip install -U planemo flake8 xmldiff
- pip install -r requirements.txt
- python setup.py install
- flake8 argparse argparse2tool click
- PYTHONPATH=$(argparse2tool_check_path -q) python examples/example.py --generate_galaxy_xml > tmp.xml
- PYTHONPATH=$(argparse2tool_check_path -q) python examples/example-sub.py --generate_galaxy_xml > tmp-sub.xml
- xmldiff tmp.xml examples/example.xml
- xmldiff tmp-sub.xml examples/example-sub.xml
- planemo lint --report_level all --fail_level error --xsd tmp.xml
- PYTHONPATH=$(argparse2tool_check_path -q) python examples/example.py --generate_cwl_tool > tmp.cwl
- PYTHONPATH=$(argparse2tool_check_path -q) python examples/example-sub.py --generate_cwl_tool > tmp-sub.cwl
- sed -i 's/argparse2tool .*/argparse2tool/g' tmp.cwl tmp-sub.cwl
- diff tmp.cwl examples/example.cwl
- diff tmp-sub.cwl examples/example-sub.cwl
before_deploy:
- sed -i "s/__version__.*/__version__= '${TRAVIS_TAG}'/g" argparse2tool/__init__.py
deploy:
- provider: pypi
  user: erasche
  password:
    secure: PjtJXEgtAjPKU/dqlodk/PxR9V6izRc7Ku7Q0jJG8eQcr+u3tGTKWtGSO9ULclfEzRrZmC4ndgJMklV6TWpT9sRJon9+itOrBXxiQMHoqfZ3tRw7Iqgo4sRoTQSu810DYqgWTCTYZLkPGiHjeinAfl9tUQ2jqyhulUPOdssM2UQ=
  on:
    tags: true
    all_branches: true
    distributions: sdist bdist_wheel
    repo: erasche/argparse2tool
